### ISSUE TITLE
Dinamically add ticket types to homepage

### ISSUE THREAD

**Issue by vuletic** [sergiosuperstar/TripApp#23]
Ticket types for purchase are currently hardcoded on the home fragment. Change them so they load from the database.

**Comment by NNemanjaMM** [comment]
Treba prvo podesiti da dinamički dobavlja podatke pri otvaranju svake karte (MainActivity od linije 163, pa nadalje), pa tek onda praviti dinamički Home fragment

**Comment by vuletic** [comment]
Hoces ja da dobavim, ti da popunis?

**Comment by vuletic** [comment]
Not going to be done
